% This function mxNiDepthRealWorld, takes the Current-Depth (movie) frame 
%   and convert the information to X,Y,Z world coordinates (mm)
%
% 	X = mxNiDepthRealWorld(KinectHandles);
%
% inputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxNiCreateContext, such as main, image, IR, Depth and User node.
%
% outputs,
%   X : A Matrix of type double with size [sizex,sizey,3] with the depth
%       pixels by described worldcoordinates X,Y,Z (mm) 
%
%
% See also mxNiDepth, mxNiCreateContext, mxNiUpdateContext, mxNiPhoto,
%		mxNiInfrared, mxNiSkeleton, mxNiDeleteContext
%
% Mex-Wrapper is written by D.Kroon University of Twente (February 2011)  
