% This function mxNiInfrared, takes the Current-Infrared(movie) frame from 
%   the Kinect-Stream, and makes it available as matlab variable
%
% 	I = mxNiInfared(KinectHandles);
%
% inputs,
%   KinectHandles : Array with pointers to kinect node objects generated by
%          mxNiCreateContext, such as main, image, IR, Depth and User node.
%
% outputs,
%   I : A 2D matrix of type Uint16 with the Infared-dots, capatured by the 
%       infrared-camera which are projected by The laser-device inside 
%       the Kinect.
%
% note,
%	To go the next movie-frame use mxNiUpdateContext(KinectHandles)
%
%
% See also mxNiCreateContext, mxNiUpdateContext, mxNiDepth, mxNiPhoto,
%		mxNiSkeleton, mxNiDeleteContext
%
% Mex-Wrapper is written by D.Kroon University of Twente (February 2011)  